### ISSUE TITLE
Handle waypoint commands received by mavlink

### ISSUE THREAD

**Issue by traffael** [Octanis1/Octanis1-Mainboard-Firmware_MSP_EXP432P401RLP#14]
Mavlink can send GPS targets / waypoints to the mainboard. 
-> Command list: https://pixhawk.ethz.ch/mavlink/
-> decode those messages and add waypoint to the target list (currently in navigation module)
-> improve the implementation of target list adapted to the type of mavlink messages.

**Comment by bitmorse** [comment]
see here: http://qgroundcontrol.org/mavlink/waypoint_protocol
