### ISSUE TITLE
Process MAVLink COMMANDs sent from APM Planner

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-Mainboard-Firmware_MSP_EXP432P401RLP#19]
Mainboard must be able to respond to MAVLink commands to ARM or DISARM the autopilot. In addition to this it must forward the MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN to the UART0. http://qgroundcontrol.org/mavlink/mission_interface

**Comment by bitmorse** [comment]
relevant functions for this task:
mavlink_msg_command_ack
mavlink_msg_command_int
mavlink_msg_command_long

**Comment by traffael** [comment]
mavlink_msg_command_ack and mavlink_msg_command_long done for the necessary cases. 

Do we really need to listen to mavlink_msg_command_int ?

**Comment by bitmorse** [comment]
arm / disarm works. do the commands work or are they too long?
