### ISSUE TITLE
Write case to handle Shutdown of SBC

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-Mainboard-Firmware_MSP_EXP432P401RLP#23]

**Comment by traffael** [comment]
Upon reception of the MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN command  from APM planner (-> click Halt button), the mainboard forwards this command message to the SBC.  If the latter sends an acknowledgement, this message gets forwarded to APM planner by the mainboard. 

The mainboard considers the SBC is shut down 
- if the MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN gets confirmed/acknowledged by the SBC

OR 

- if no mavlink heartbeat of the SBC is received during the last 10 seconds.
