### ISSUE TITLE
Write case to handle START THE MISSION

### ISSUE THREAD

**Issue by bitmorse** [Octanis1/Octanis1-Mainboard-Firmware_MSP_EXP432P401RLP#24]

**Comment by traffael** [comment]
After sending all waypoints, the mission can be started by ARMING the system. This will make the rover drive to waypoint 0 (home) and stop there until the SBC has finished booting and is sending heartbeats . The mainboard then sends an ARM command to the SBC, and, once this gets confirmed, starts driving to the next waypoints in the list.

The SBC starts recording when it is armed.
